# Generated by Django 2.2 on 2023-11-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Age', models.IntegerField(default=None)),
                ('Phone_no', models.IntegerField(default=None, max_length=10)),
            ],
        ),
    ]
