# Generated by Django 2.2 on 2023-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone_no',
            field=models.IntegerField(default=None),
        ),
    ]
